### PR TITLE
Add limit param to key_metrics endpoint

### PR DESCRIPTION
**Pull request by ravic1995**
- Add limit param to limit the data required and also reduce call latency
- Can extend this implementation to other endpoints as well. 
- Set default limit to 0

### CODE REVIEW

**Comment by JerBouma** [comment]
Could you elaborate what this does exactly?

**Comment by ravic1995** [comment]
Sorry I did not elaborate earlier 
https://financialmodelingprep.com/developer/docs 
These API allow the adding of limit to the requets URLs
That would reduce the data response returned. As this can be used to make the calls efficient as some times not all data is required and can be used to better query the data-set. 

eg: I would like to only get the most recent year data, hence wondering if we can implement the limit param.

**Comment by JerBouma** [comment]
Thanks, I will also add this to other functions.

**Comment by JerBouma** [comment]
Please update to 0.2.10 to obtain the fix!

**Pull request merged**
